name: Market Sentinel Daily Analysis

on:
  schedule:
  # Roda a cada 3 horas, das 09:00 UTC (06:00 BRT) até as 21:00 UTC (18:00 BRT)
    - cron: '0 9-21/3 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar Agente Financeiro
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python script.py
